version: '3.4'

services:
  solboxconnector:
    image: solboxconnector
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - SOLBOX_USERNAME=felix.eichenberger@gmail.com
      - SOLBOX_PASSWORD=UiPLnHhSdjn6gd
      - TZ=Europe/Zurich
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 solbox.py "]
    ports:
      - 5678:5678
