version: '3.4'

services:
  solboxconnector:
    image: solboxconnector
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SOREL_USERNAME: ${SOLBOX_USERNAME}
      SOREL_PASSWORD: ${SOLBOX_PASSWORD}
      TZ: Europe/Zurich
      MQTT_BROKER_HOST: 192.168.110.50 
      MQTT_BROKER_PORT: 1883
    restart: unless-stopped
