[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.docker-build]
command = "docker-compose"
args = ["build", "exporter"]

[tasks.docker-tag]
command = "docker"
args = ["tag", "solbox-mqtt-exporter", "nightfury5432/solbox-mqtt-exporter"]

[tasks.docker-push]
command = "docker"
args = ["push", "nightfury5432/solbox-mqtt-exporter"]

[tasks.deploy]
dependencies = [
    "docker-build",
    "docker-tag",
    "docker-push"
]
